# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'nome1' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for nome1
  pod 'Firebase', '>=2.5.0'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'
  pod 'Firebase/Crash'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
end
